#! /bin/zsh
# This file is a set of alise used for making the others more readable

alias exists='type > /dev/null'
alias running='pidof'
alias os="uname -r|sed 's/^.*[-]//'"
alias murrays="hostname|grep uDH"
