#!/bin/bash

##
# Position screens
##

sleep   1 && xrandr --output DP-0 --rotate left
sleep   2 && xrandr --output DP-0 --rotate left

##
# Start Transparency
##

sleep   2 && picom &

##
# Move Desktops to the correct screens
##

sleep   2 && i3-msg 'workspace   2' &
sleep   3 && i3-msg 'workspace   1' &

##
# Programs
##

sleep   5 && i3-msg 'workspace 2; exec xfce4-terminal -e "tmux attach"' &
sleep   10 && i3-msg 'workspace 2; exec anki' &
#sleep  10 && xscreensaver &
sleep  20 && i3-msg 'workspace 0; exec xfce4-terminal -e "barriers --disable-crypto -f"' &
sleep  35 && i3-msg 'workspace 11; exec thunderbird' &

#sleep  60 && i3-msg 'workspace  3; exec ~/steam/steam/steam.sh' &

#sleep   5 && i3-msg 'workspace 11; exec xfce4-terminal --command=alsamixer' &
#sleep   7 && i3-msg 'exec xfce-terminal --command=pianobar' &

#sleep  62 && i3-msg 'workspace 12; exec kvirc4 --nosplash' &
#sleep  64 && i3-msg 'layout tabbed' &

#sleep  60 && i3-msg 'workspace 12; exec firefox' &
#sleep  68 && i3-msg 'layout tabbed' &

#sleep  80 && i3-msg 'workspace  1; exec google-chrome-stable' &
#wait for the tabs to load
#sleep 100 && i3-msg 'layout tabbed' &

##
# Move to main workspace
##

sleep 120 && i3-msg 'workspace 11' &
sleep 121 && i3-msg 'workspace  1' &
sleep 122 && i3-msg 'workspace  2' &

exec dbus-launch --exit-with-session i3
