;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				c-electric-slash
				indent-for-tab-command
				ispell-word
				kill-region
				markdown-end-of-line
				markdown-outdent-or-delete
				org-beginning-of-line
				org-cycle
				org-end-of-line
				org-fill-paragraph
				org-force-self-insert
				org-kill-line
				org-metaright
				org-return
				org-self-insert-command
				org-yank
				))

(setq mc/cmds-to-run-once
      '(
				ask-before-closing
				))
