#! /usr/bin/env zsh

if [[ -e /run/motd.dynamic ]]; then
		/usr/bin/env cat /run/motd.dynamic
fi

if [[ -e /etc/motd ]]; then
	/usr/bin/env cat /etc/motd
else if type anyfetch >/dev/null ; then
	anyfetch
else if type neofetch >/dev/null ; then
	neofetch --color_blocks off
else # if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	if type figlet > /dev/null; then
		figlet -f script "Hello $USER.  Welcome to $HOST." -t
	elif type toilet > /dev/null; then
		toilet -f script "Hello $USER.  Welcome to $HOST." -t
	else
		echo "Hello $USER.  Welcome to $HOST."
		echo
	fi
fi; fi; fi

if type weather >/dev/null && type paste >/dev/null; then
	if type cal > /dev/null; then
	# TODO: check cal version instead?
    if uname -a |grep -Ei "(ubuntu|debian)" > /dev/null; then
				paste <(cal) <(weather)
		else
				paste <(cal --color=always) <(weather)
		fi
	else
			weather
	fi
else if type cal > /dev/null; then
    cal -3
fi; fi
